package co.edu.uniquindio.programaAdministrarCursos.model;

public enum AccionEnum {
	LOGGEAR_ESTUDIANTE,
	REGISTRAR_ACCION,
	REGISTRAR_ESTUDIANTE,
	REGISTRAR_INSTRUCTOR,
	REGISTRAR_CREDITO_DEPORTIVO,
	REGISTRAR_CREDITO_ACADEMICO,
	REGISTRAR_CREDITO_CULTURAL,
	HACER_BACKUP,
	ACTUALIZAR_ESTUDIANTE,
	ACTUALIZAR_INSTRUCTOR,
	ACTUALIZAR_CREDITO,
	OBTENER_CREDITOS,
	BORRAR_ESTUDIANTE,
	BORRAR_INSTRUCTOR,
	BORRAR_CREDITO,
	OBTENER_ESTUDIANTES,
	OBTENER_INSTRUCTORES,
	VERIFICAR_ID_ESTUDIANTE,
	VERIFICAR_ID_INSTRUCTOR,
	VERIFICAR_NOMBRE_CREDITO,
	VERIFICAR_CORREO_ESTUDIANTE,
	VERIFICAR_CORREO_INSTRUCTOR,
	CARGAR_DATOS_TXT,
	GUARDAR_DATOS_TXT,
	CARGAR_BACKUP
	
	
	

}
